name: ZEnchantments-Basic
main: io.zivoric.enchantmentcore.basic.BasicEnchPlugin
version: 1.3.0
api-version: 1.13
depend: [ZEnchantmentCore]
#commands:
#    zenchant:
#        description: Enchants with Z-Enchantment.
#        usage: /zenchant
#permissions:
#  zenchants.sample:
#    description: Sample permission.
#    default: op